import * as React from "react";
import * as Types from "./types";

declare function ClubPage(props: {
  as?: React.ElementType;
  titlePage?: React.ReactNode;
  clubName?: React.ReactNode;
  disconnectButtonProps?: Types.Devlink.RuntimeProps;
  linkDashboard?: Types.Basic.Link;
  linkManage?: Types.Basic.Link;
  linkCalendar?: Types.Basic.Link;
  linkBilling?: Types.Basic.Link;
  linkClub?: Types.Basic.Link;
  linkSettings?: Types.Basic.Link;
  styleClub?: Types.Devlink.RuntimeProps;
  street?: React.ReactNode;
  street1?: React.ReactNode;
  hasStreet1?: Types.Visibility.VisibilityConditions;
  zipCode?: React.ReactNode;
  city?: React.ReactNode;
  country?: React.ReactNode;
  email?: React.ReactNode;
  phone?: React.ReactNode;
  website?: React.ReactNode;
  componentSwitch?: Types.Devlink.Slot;
  componentLogoClub?: Types.Devlink.Slot;
  standardPriceList?: Types.Devlink.Slot;
  weekPriceList?: Types.Devlink.Slot;
  specialPriceList?: Types.Devlink.Slot;
  standardOpeningList?: Types.Devlink.Slot;
  weekOpeningList?: Types.Devlink.Slot;
  specialOpeningList?: Types.Devlink.Slot;
  componentSites?: Types.Devlink.Slot;
  componentCourts?: Types.Devlink.Slot;
  textfieldClubName?: Types.Devlink.Slot;
  textfieldClubPhone?: Types.Devlink.Slot;
  textfieldClubMail?: Types.Devlink.Slot;
  textfieldClubWebsite?: Types.Devlink.Slot;
  isEditing?: Types.Visibility.VisibilityConditions;
  isLoading?: Types.Visibility.VisibilityConditions;
  isSuccess?: Types.Visibility.VisibilityConditions;
  isError?: Types.Visibility.VisibilityConditions;
  textfieldClubAddress?: Types.Devlink.Slot;
}): React.JSX.Element;
